### PR TITLE
Pass through TableDependency as sender in delegate

### PR DESCRIPTION
**Pull request by igitur**
I should probably add a test for this, but I'm a bit overwhelmed with the number of test classes. Can you perhaps recommend an existing test to modify to test this?

### CODE REVIEW

**Comment by igitur** [comment]
@christiandelbianco Would you by any chance be able to review my PRs sometime?

**Comment by christiandelbianco** [comment]
Thanks

**Comment by igitur** [comment]
Pleasure, but I still wanted to add a unit test for this. As per the original comment, I was looking for guidance as to where the most appropriate place is for a test.

**Comment by christiandelbianco** [comment]
hi, you can create a new test class in https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/tree/master/Tests/TableDependency.SqlClient.IntegrationTest project

**Pull request merged**
